name: Publish

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python install
        uses: actions/setup-python@v5
      - name: Download release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download ${{ github.event.release.tag_name }} --repo ${{ github.repository }} --pattern "*.tar.gz" --dir ./dist
          gh release download ${{ github.event.release.tag_name }} --repo ${{ github.repository }} --pattern "*.whl" --dir ./dist
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          python3 -m pip install twine
          python3 -m twine upload dist/*.tar.gz dist/*.whl
      - name: Publish to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 -m pip install mkdocs mkdocs-techdocs-core
          python3 -m pip install dist/*.whl
          mkdocs gh-deploy --force
